In [1]:
import numpy as np

## Execution speed

In [2]:
%%capture timeit_results

%timeit x = range(1000)

%timeit y = np.arange(1,1000)

In [3]:
print(timeit_results)

The slowest run took 6.71 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 288 ns per loop
The slowest run took 7.37 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.49 us per loop



## Generating lists/arrays

### Summary
  - **Functions used:-** arange, linspace, zeros, ones, random,
  - 

In [8]:
np.random.seed(42)

In [9]:
np.arange(1,5)

array([1, 2, 3, 4])

In [12]:
np.linspace(1,5)

array([ 1.        ,  1.08163265,  1.16326531,  1.24489796,  1.32653061,
        1.40816327,  1.48979592,  1.57142857,  1.65306122,  1.73469388,
        1.81632653,  1.89795918,  1.97959184,  2.06122449,  2.14285714,
        2.2244898 ,  2.30612245,  2.3877551 ,  2.46938776,  2.55102041,
        2.63265306,  2.71428571,  2.79591837,  2.87755102,  2.95918367,
        3.04081633,  3.12244898,  3.20408163,  3.28571429,  3.36734694,
        3.44897959,  3.53061224,  3.6122449 ,  3.69387755,  3.7755102 ,
        3.85714286,  3.93877551,  4.02040816,  4.10204082,  4.18367347,
        4.26530612,  4.34693878,  4.42857143,  4.51020408,  4.59183673,
        4.67346939,  4.75510204,  4.83673469,  4.91836735,  5.        ])

In [13]:
np.linspace(1,5,num=10)

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [30]:
np.linspace(1,5,num=10, endpoint=False)

array([ 1. ,  1.4,  1.8,  2.2,  2.6,  3. ,  3.4,  3.8,  4.2,  4.6])

In [29]:
np.linspace(1,5,num=10, endpoint=False, dtype=np.int)

array([1, 1, 1, 2, 2, 3, 3, 3, 4, 4])

In [24]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [31]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [28]:
np.random.random((2,3))

array([[ 0.03438852,  0.9093204 ,  0.25877998],
       [ 0.66252228,  0.31171108,  0.52006802]])

## Statistical Analysis
  - **Functions used:-** max,

In [21]:
data = np.random.random((2,3))

In [22]:
data

array([[ 0.30461377,  0.09767211,  0.68423303],
       [ 0.44015249,  0.12203823,  0.49517691]])

In [32]:
data.max()

0.68423302651215689

In [36]:
# row wise
data.max(axis=0)

array([ 0.44015249,  0.12203823,  0.68423303])

In [37]:
# column wise
data.max(axis=1)

array([ 0.68423303,  0.49517691])

In [38]:
np.min(data), np.mean(data), np.median(data), np.std(data), np.sum(data)

(0.09767211400638387,
 0.35731442473126029,
 0.37238313145648599,
 0.20748106615819384,
 2.1438865483875618)

In [39]:
data.reshape((3,2))

array([[ 0.30461377,  0.09767211],
       [ 0.68423303,  0.44015249],
       [ 0.12203823,  0.49517691]])

In [40]:
data.reshape((6,1)), data.reshape((6,))

(array([[ 0.30461377],
        [ 0.09767211],
        [ 0.68423303],
        [ 0.44015249],
        [ 0.12203823],
        [ 0.49517691]]),
 array([ 0.30461377,  0.09767211,  0.68423303,  0.44015249,  0.12203823,
         0.49517691]))

In [42]:
data.ravel(), data.flatten()

(array([ 0.30461377,  0.09767211,  0.68423303,  0.44015249,  0.12203823,
         0.49517691]),
 array([ 0.30461377,  0.09767211,  0.68423303,  0.44015249,  0.12203823,
         0.49517691]))